{% set name = "cf-plot" %}
{% set version = "3.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0552bd7a4896e3e5677fcba688d07d2021766912c288b89c6474af04c31ec1b7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - cartopy >=0.17.0
    - cf-python >=3.9.0
    - matplotlib-base >=3.1.0
    - scipy >=1.4.0

test:
  imports:
    - cfplot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ajheaps/cf-plot
  summary: Climate contour, vector and line plots in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
