{% set name = "cf-plot" %}
{% set version = "3.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41a1920d2a24e2fdf97bd7f232b0e9e2f9573a533525a0199cac3d4c15c7c2d9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - cartopy >=0.17.0
    - cf-python >=3
    - matplotlib-base >=3.1.0
    - scipy >=1.4.0

test:
  imports:
    - cfplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ajheaps/cf-plot
  summary: Climate contour, vector and line plots in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
