{% set name = "cf-plot" %}
{% set version = "3.1.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4d73668af79002d2b4db2b3d003eeac223e4d81efabe86c433eb45ebadc756f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cartopy >=0.17.0
    - cf-python >=3.9.0
    - matplotlib-base >=3.1.0
    - scipy >=1.4.0

test:
  imports:
    - cfplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ajheaps/cf-plot
  summary: Climate contour, vector and line plots in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
