{% set name = "cf-plot" %}
{% set version = "3.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: aa86a09c22ee5d5e5b0949735208a38441848d3fe6e800b48e592bd52fe7d781

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - cartopy >=0.22.0
    - cf-python >=3.17.0
    - matplotlib-base >=3.1.0
    - scipy >=1.4.0

test:
  imports:
    - cfplot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ajheaps/cf-plot
  summary: Climate contour, vector and line plots in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
