{% set name = "cf-plot" %}
{% set version = "3.0.20" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12ccff548b99414b365304772c36c6bec36d0e45888c9f7a5f081619c37553b8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - cartopy >=0.17.0
    - cf-python >=3
    - matplotlib-base >=3.1.0
    - scipy >=1.4.0

test:
  imports:
    - cfplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ajheaps/cf-plot
  summary: Climate contour, vector and line plots in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
